# Generated by Django 4.0.4 on 2022-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_column='Market', max_length=20)),
                ('type', models.CharField(choices=[('RAW', 'Raw'), ('RAW^2', 'Raw Squared'), ('M1EMA1', 'First Moment First Exponential Moving Average'), ('M1EMA2', 'First Moment Second Exponential Moving Average'), ('M1EMA3', 'First Moment Third Exponential Moving Average'), ('M1TEMA', 'First Moment Triple Exponential Moving Average'), ('M2EMA1', 'Second Moment First Exponential Moving Average'), ('M2EMA2', 'Second Moment Second Exponential Moving Average'), ('M2EMA3', 'Second Moment Third Exponential Moving Average'), ('M2TEMA', 'Second Moment Triple Exponential Moving Average'), ('SDEMA1', 'Standard Deviation First Exponential Moving Average'), ('SDEMA2', 'Standard Deviation Second Exponential Moving Average'), ('SDEMA3', 'Standard Deviation Third Exponential Moving Average'), ('SDTEMA', 'Standard Deviation Triple Exponential Moving Average')], db_column='Type', max_length=6)),
                ('value', models.DecimalField(db_column='Value', decimal_places=28, max_digits=38)),
                ('time', models.DecimalField(db_column='Time', decimal_places=6, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='SpotMarket',
            fields=[
                ('name', models.CharField(db_column='SpotName', max_length=20, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(db_column='Enabled')),
                ('price_increment', models.DecimalField(db_column='PriceIncrement', decimal_places=9, max_digits=13)),
                ('size_increment', models.DecimalField(db_column='SizeIncrement', decimal_places=6, max_digits=13)),
                ('min_provide_size', models.DecimalField(db_column='MinProvideSize', decimal_places=6, max_digits=13)),
                ('is_etf_market', models.BooleanField(db_column='IsETFMarket')),
                ('base_currency', models.CharField(db_column='BaseCurrency', max_length=10)),
                ('quote_currency', models.CharField(db_column='QuoteCurrency', max_length=10)),
                ('large_order_threshold', models.DecimalField(db_column='LargeOrderThreshold', decimal_places=5, max_digits=10)),
            ],
        ),
    ]
