# Generated by Django 4.0.4 on 2022-05-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotMarket',
            fields=[
                ('name', models.CharField(db_column='SpotName', max_length=20, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(db_column='Enabled')),
                ('price_increment', models.DecimalField(db_column='PriceIncrement', decimal_places=8, max_digits=9)),
                ('size_increment', models.DecimalField(db_column='SizeIncrement', decimal_places=6, max_digits=7)),
                ('min_provide_size', models.DecimalField(db_column='MinProvideSize', decimal_places=6, max_digits=7)),
                ('base_currency', models.CharField(db_column='BaseCurrency', max_length=10)),
                ('is_etf_market', models.BooleanField(db_column='IsETFMarket')),
                ('quote_currency', models.CharField(db_column='QuoteCurrency', max_length=10)),
                ('large_order_threshold', models.DecimalField(db_column='LargeOrderThreshold', decimal_places=5, max_digits=10)),
            ],
        ),
    ]
