# Generated by Django 4.0.4 on 2022-05-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotmarket',
            name='price_increment',
            field=models.DecimalField(db_column='PriceIncrement', decimal_places=9, max_digits=9),
        ),
    ]
