# Generated by Django 4.0.4 on 2022-06-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_candlestick_delete_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='time',
            field=models.DateTimeField(db_column='Time'),
        ),
    ]
