# Generated by Django 4.0.4 on 2022-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_spotmarket_min_provide_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotmarket',
            name='price_increment',
            field=models.DecimalField(db_column='PriceIncrement', decimal_places=9, max_digits=13),
        ),
    ]
