# Generated by Django 4.0.4 on 2022-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_spottrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottrade',
            name='capital',
            field=models.DecimalField(db_column='Capital', decimal_places=9, max_digits=38),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='price',
            field=models.DecimalField(db_column='Price', decimal_places=9, max_digits=38),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='size',
            field=models.DecimalField(db_column='Size', decimal_places=9, max_digits=38),
        ),
    ]
