# Generated by Django 4.0.4 on 2022-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_spottrade_capital_alter_spottrade_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottrade',
            name='time',
            field=models.DecimalField(db_column='Time', decimal_places=3, max_digits=13),
        ),
    ]
