# Generated by Django 4.0.4 on 2022-05-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_datapoint_alter_spottrade_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.RemoveField(
            model_name='spottrade',
            name='capital',
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='id',
            field=models.DecimalField(db_column='Id', decimal_places=0, max_digits=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='market',
            field=models.CharField(db_column='Market', max_length=20),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='side',
            field=models.CharField(db_column='Side', max_length=4),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='time',
            field=models.DateTimeField(db_column='Time'),
        ),
    ]
