# Generated by Django 4.0.4 on 2022-05-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_delete_datapoint_remove_spottrade_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RAW', 'Raw'), ('RAW^2', 'Raw Squared'), ('M1EMA1', 'First Moment First Exponential Moving Average'), ('M1EMA2', 'First Moment Second Exponential Moving Average'), ('M1EMA3', 'First Moment Third Exponential Moving Average'), ('M1TEMA', 'First Moment Triple Exponential Moving Average'), ('M2EMA1', 'Second Moment First Exponential Moving Average'), ('M2EMA2', 'Second Moment Second Exponential Moving Average'), ('M2EMA3', 'Second Moment Third Exponential Moving Average'), ('M2TEMA', 'Second Moment Triple Exponential Moving Average')], db_column='Type', max_length=6)),
                ('value', models.DecimalField(db_column='Value', decimal_places=9, max_digits=38)),
                ('time', models.DecimalField(db_column='Time', decimal_places=6, max_digits=16)),
            ],
        ),
    ]
